/* lanehash_aes - C port of the Rust definition (lanehash/src/aes/{spec,lanes,short}.rs).
 *
 *   len <= 64: two to five protected 64x64->128 multiplies over the input words with
 *              per-seed secrets, then one unprotected fold per output half.
 *   len >  64: L = 4 (len <= 256) / 8 (len <= 1024) / 16 lanes; 16-byte block j enters
 *              lane j mod L as data and round key, t = AES(t ^ b) ^ b; the last 16*L
 *              bytes, XORed with the broadcast length, close each lane the same way;
 *              three constant-key rounds per lane; lanes added; three finaliser rounds,
 *              the first keyed with the length.
 *
 * Backends, chosen at compile time, all bit-identical:
 *   LANEHASH_AES_PORTABLE, or no AES intrinsics: T-table software AES
 *              (lanehash_aes_ttables.h, generated by gen_ttables.py).
 *   __AES__ (-maes, MSVC /arch:AVX2+): one lane per xmm register.
 *   __VAES__ && __AVX2__: two lanes per ymm register.
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */
#include "lanehash_aes.h"
#include <string.h>

#include "lanehash_aes_constants.h"

#if !defined(LANEHASH_AES_PORTABLE) && (defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86))
#  if defined(__VAES__) && defined(__AVX2__)
#    define LH_VAES 1
#    define LH_AESNI 1
#  elif defined(__AES__) || (defined(_MSC_VER) && defined(__AVX2__))
#    define LH_AESNI 1
#  endif
#endif
#if defined(LH_AESNI)
#  include <immintrin.h>
#endif

/* Keep a loaded block in a register: gcc otherwise folds the load into the memory
 * operands of both the XOR and the AES instruction and loads every block twice. */
#if defined(__GNUC__)
#  define LH_REG(v) __asm__("" : "+x"(v))
#else
#  define LH_REG(v) ((void)0)
#endif
/* Absorb one 16-byte block at q into lane t: t = AES(t ^ b) ^ b, the block pinned
 * in a register (see LH_REG). */
#define LH_ABSORB_REG(t, q) do {                                                        \
        __m128i b_ = _mm_loadu_si128((const __m128i *)(q));                             \
        LH_REG(b_);                                                                     \
        (t) = _mm_aesenc_si128(_mm_xor_si128((t), b_), b_);                             \
    } while (0)

#if defined(__GNUC__)
#  define LH_NOINLINE __attribute__((noinline))
#  define LH_INLINE static inline __attribute__((always_inline))
#elif defined(_MSC_VER)
#  define LH_NOINLINE __declspec(noinline)
#  define LH_INLINE static __forceinline
#else
#  define LH_NOINLINE
#  define LH_INLINE static inline
#endif

/* Lane loops must be fully unrolled so the lane state stays in registers. */
#if defined(__clang__)
#  define LH_UNROLL _Pragma("clang loop unroll(full)")
#elif defined(__GNUC__) && __GNUC__ >= 8
#  define LH_UNROLL _Pragma("GCC unroll 16")
#else
#  define LH_UNROLL
#endif

/* ------------------------------------------------------------------------- */
/* scalar helpers                                                             */

#if defined(__SIZEOF_INT128__) && !defined(LANEHASH_AES_NO_INT128)
__extension__ typedef unsigned __int128 lh_u128;
static inline void lh_mul128(uint64_t a, uint64_t b, uint64_t *lo, uint64_t *hi) {
    lh_u128 r = (lh_u128)a * b;
    *lo = (uint64_t)r;
    *hi = (uint64_t)(r >> 64);
}
#elif defined(_MSC_VER) && (defined(_M_X64) || defined(_M_ARM64))
#  include <intrin.h>
static inline void lh_mul128(uint64_t a, uint64_t b, uint64_t *lo, uint64_t *hi) {
    *lo = _umul128(a, b, hi);
}
#else
static inline void lh_mul128(uint64_t a, uint64_t b, uint64_t *lo, uint64_t *hi) {
    uint64_t a0 = (uint32_t)a, a1 = a >> 32, b0 = (uint32_t)b, b1 = b >> 32;
    uint64_t p00 = a0 * b0, p01 = a0 * b1, p10 = a1 * b0, p11 = a1 * b1;
    uint64_t mid = (p00 >> 32) + (uint32_t)p01 + (uint32_t)p10;
    *lo = (mid << 32) | (uint32_t)p00;
    *hi = p11 + (p01 >> 32) + (p10 >> 32) + (mid >> 32);
}
#endif

static inline uint64_t lh_fold(uint64_t a, uint64_t b) {
    uint64_t lo, hi;
    lh_mul128(a, b, &lo, &hi);
    return lo ^ hi;
}

/* protected mum: (a ^ lo, b ^ hi) */
static inline void lh_mum(uint64_t *a, uint64_t *b) {
    uint64_t lo, hi;
    lh_mul128(*a, *b, &lo, &hi);
    *a ^= lo;
    *b ^= hi;
}

static inline uint64_t lh_rotl(uint64_t x, unsigned r) {
    return r ? ((x << r) | (x >> (64 - r))) : x;
}

static inline uint64_t lh_le64(const uint8_t *p) {
    uint64_t v;
    memcpy(&v, p, 8);
#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
    v = __builtin_bswap64(v);
#endif
    return v;
}
static inline uint64_t lh_le32(const uint8_t *p) {
    uint32_t v;
    memcpy(&v, p, 4);
#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
    v = __builtin_bswap32(v);
#endif
    return (uint64_t)v;
}
static inline void lh_put64(uint8_t *p, uint64_t v) {
#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
    v = __builtin_bswap64(v);
#endif
    memcpy(p, &v, 8);
}

/* ------------------------------------------------------------------------- */
/* short path, len <= 64                                                      */

#define LH_TOP UINT64_C(0x8000000000000000)

/* per-seed secrets: rotations of ks = fold(seed ^ K0, K1), XORed with distinct
 * constants, top bit forced (never 0 or 1) */
static inline void lh_secrets(uint64_t seed, uint64_t k[8]) {
    uint64_t ks = lh_fold(seed ^ LH_K0, LH_K1);
    unsigned j;
    LH_UNROLL
    for (j = 0; j < 8; j++)
        k[j] = (lh_rotl(ks, 9 * j) ^ LH_KS[j]) | LH_TOP;
}

/* Final folds: lo always; hi only when hip != NULL (constant per caller after inlining). */
static inline uint64_t lh_finish(uint64_t x, uint64_t y, const uint64_t k[8], uint64_t ln, uint64_t *hip) {
    if (hip)
        *hip = lh_fold(x ^ k[4], y ^ k[5] ^ ln);
    return lh_fold(x ^ k[2] ^ ln, y ^ k[3]);
}

static inline uint64_t lh_short_le16(const uint8_t *p, size_t len, uint64_t seed, uint64_t *hip) {
    uint64_t k[8], w0, w1 = 0, ln = (uint64_t)len;
    lh_secrets(seed, k);
    if (len == 0)
        w0 = 0;
    else if (len <= 3)
        w0 = (uint64_t)p[0] | ((uint64_t)p[len / 2] << 8) | ((uint64_t)p[len - 1] << 16);
    else if (len <= 8)
        w0 = lh_le32(p) | (lh_le32(p + len - 4) << 32);
    else {
        w0 = lh_le64(p);
        w1 = lh_le64(p + len - 8);
    }
    w0 ^= k[0];
    w1 ^= k[1] ^ ln;
    lh_mum(&w0, &w1);
    return lh_finish(w0, w1, k, ln, hip);
}

static inline uint64_t lh_short_le32(const uint8_t *p, size_t len, uint64_t seed, uint64_t *hip) {
    uint64_t k[8], ln = (uint64_t)len;
    uint64_t a0, b0, a1, b1;
    lh_secrets(seed, k);
    a0 = lh_le64(p) ^ k[0];
    b0 = lh_le64(p + 8) ^ k[1];
    a1 = lh_le64(p + len - 16) ^ k[2];
    b1 = lh_le64(p + len - 8) ^ k[3] ^ ln;
    lh_mum(&a0, &b0);
    lh_mum(&a1, &b1);
    return lh_finish(a0 ^ b1, b0 ^ a1, k, ln, hip);
}

static inline uint64_t lh_short_le64(const uint8_t *p, size_t len, uint64_t seed, uint64_t *hip) {
    uint64_t k[8], ln = (uint64_t)len;
    uint64_t a0, b0, a1, b1, a2, b2, a3, b3;
    lh_secrets(seed, k);
    a0 = lh_le64(p) ^ k[0];
    b0 = lh_le64(p + 8) ^ k[1];
    a1 = lh_le64(p + 16) ^ k[2];
    b1 = lh_le64(p + 24) ^ k[3];
    a2 = lh_le64(p + len - 32) ^ k[4];
    b2 = lh_le64(p + len - 24) ^ k[5];
    a3 = lh_le64(p + len - 16) ^ k[6];
    b3 = lh_le64(p + len - 8) ^ k[7] ^ ln;
    lh_mum(&a0, &b0);
    lh_mum(&a1, &b1);
    lh_mum(&a2, &b2);
    lh_mum(&a3, &b3);
    return lh_finish(a0 ^ b1 ^ a2 ^ b3, b0 ^ a1 ^ b2 ^ a3, k, ln, hip);
}

/* ------------------------------------------------------------------------- */
/* lane path, len > 64: portable software AES                                 */

#if !defined(LH_AESNI)

#include "lanehash_aes_ttables.h"

/* a block as two little-endian halves: columns 0,1 in lo, 2,3 in hi */
typedef struct { uint64_t lo, hi; } lh_blk;

/* one AES encryption round: MixColumns(ShiftRows(SubBytes(x))) ^ k (== AESENC),
 * 16 T-table lookups (lanehash/src/soft.rs) */
LH_INLINE uint32_t lh_col(uint32_t a, uint32_t b, uint32_t c, uint32_t d) {
    return LH_TE[0][a & 0xff] ^ LH_TE[1][(b >> 8) & 0xff] ^ LH_TE[2][(c >> 16) & 0xff] ^ LH_TE[3][d >> 24];
}
LH_INLINE lh_blk lh_round(lh_blk x, lh_blk k) {
    uint32_t c0 = (uint32_t)x.lo, c1 = (uint32_t)(x.lo >> 32), c2 = (uint32_t)x.hi, c3 = (uint32_t)(x.hi >> 32);
    uint32_t y0 = lh_col(c0, c1, c2, c3), y1 = lh_col(c1, c2, c3, c0), y2 = lh_col(c2, c3, c0, c1), y3 = lh_col(c3, c0, c1, c2);
    lh_blk o;
    o.lo = (y0 | (uint64_t)y1 << 32) ^ k.lo;
    o.hi = (y2 | (uint64_t)y3 << 32) ^ k.hi;
    return o;
}

static inline lh_blk lh_load(const uint8_t *p) {
    lh_blk b;
    b.lo = lh_le64(p);
    b.hi = lh_le64(p + 8);
    return b;
}
static inline lh_blk lh_xor(lh_blk a, lh_blk b) {
    a.lo ^= b.lo;
    a.hi ^= b.hi;
    return a;
}
static inline lh_blk lh_bcast(uint64_t v) {
    lh_blk b;
    b.lo = v;
    b.hi = v;
    return b;
}
static inline lh_blk lh_const(int i) {
    return lh_load(LH_C[i]);
}
/* 64-bit lane-wise add */
static inline lh_blk lh_add(lh_blk a, lh_blk b) {
    a.lo += b.lo;
    a.hi += b.hi;
    return a;
}
/* absorb: t = R(t ^ b, b) */
LH_INLINE lh_blk lh_absorb(lh_blk t, lh_blk b) {
    return lh_round(lh_xor(t, b), b);
}

static lh_blk lh_lanes(const uint8_t *p, size_t len, uint64_t seed, unsigned L) {
    lh_blk t[16], sd = lh_bcast(seed), ln = lh_bcast((uint64_t)len), acc;
    size_t n = (len + 15) / 16, m = n - L, j;
    const uint8_t *c = p + len - 16 * L;
    unsigned i, r;
    for (i = 0; i < L; i++)
        t[i] = lh_xor(sd, lh_const((int)i));
    for (j = 0; j + L <= m; j += L) /* whole steps: block j + i -> lane i */
        for (i = 0; i < L; i++)
            t[i] = lh_absorb(t[i], lh_load(p + 16 * (j + i)));
    for (i = 0; j < m; j++, i++)
        t[i] = lh_absorb(t[i], lh_load(p + 16 * j));
    for (i = 0; i < L; i++)
        t[i] = lh_absorb(t[i], lh_xor(lh_load(c + 16 * i), ln));
    for (r = 0; r < 3; r++)
        for (i = 0; i < L; i++)
            t[i] = lh_round(t[i], lh_const(40 + (int)r));
    acc = t[0];
    for (i = 1; i < L; i++)
        acc = lh_add(acc, t[i]);
    acc = lh_round(acc, lh_xor(lh_const(24), ln));
    acc = lh_round(acc, lh_const(25));
    return lh_round(acc, lh_const(26));
}
static inline uint64_t lh_lanes64(const uint8_t *p, size_t len, uint64_t seed, unsigned L) {
    return lh_lanes(p, len, seed, L).lo;
}
static inline void lh_lanes128(const uint8_t *p, size_t len, uint64_t seed, unsigned L, uint8_t *out) {
    lh_blk r = lh_lanes(p, len, seed, L);
    lh_put64(out, r.lo);
    lh_put64(out + 8, r.hi);
}

#else /* LH_AESNI */

/* ------------------------------------------------------------------------- */
/* lane path: AES-NI, one lane per xmm (L = 4, 8, 16 via a generating macro)  */

#define LH_C128(i) _mm_loadu_si128((const __m128i *)LH_C[i])

static inline __m128i lh_finish128(__m128i acc, uint64_t len) {
    __m128i ln = _mm_set1_epi64x((long long)len);
    acc = _mm_aesenc_si128(acc, _mm_xor_si128(LH_C128(24), ln));
    acc = _mm_aesenc_si128(acc, LH_C128(25));
    return _mm_aesenc_si128(acc, LH_C128(26));
}

#define LH_DEFINE_XMM(NAME, L, ABSORB)                                                        \
static inline __m128i NAME(const uint8_t *p, size_t len, uint64_t seed) {                \
    __m128i t[L], sd = _mm_set1_epi64x((long long)seed), ln = _mm_set1_epi64x((long long)len); \
    size_t n = (len + 15) / 16, m = n - (L), full = m / (L), rem = m % (L), j;           \
    const uint8_t *c = p + len - 16 * (L);                                              \
    __m128i acc;                                                                        \
    unsigned i;                                                                         \
    LH_UNROLL for (i = 0; i < (L); i++)                                                           \
        t[i] = _mm_xor_si128(sd, LH_C128(i));                                           \
    for (j = 0; j < full; j++, p += 16 * (L))                                           \
        LH_UNROLL for (i = 0; i < (L); i++)                                             \
            ABSORB(t[i], p + 16 * i);                                                   \
    LH_UNROLL for (i = 0; i < rem; i++)                                                 \
        ABSORB(t[i], p + 16 * i);                                                                                   \
    LH_UNROLL for (i = 0; i < (L); i++) {                                                         \
        __m128i e = _mm_xor_si128(_mm_loadu_si128((const __m128i *)(c + 16 * i)), ln);  \
        LH_REG(e);                                                                      \
        t[i] = _mm_aesenc_si128(_mm_xor_si128(t[i], e), e);                             \
    }                                                                                   \
    LH_UNROLL for (i = 0; i < (L); i++) {                                                         \
        t[i] = _mm_aesenc_si128(t[i], LH_C128(40));                                     \
        t[i] = _mm_aesenc_si128(t[i], LH_C128(41));                                     \
        t[i] = _mm_aesenc_si128(t[i], LH_C128(42));                                     \
    }                                                                                   \
    acc = t[0];                                                                         \
    for (i = 1; i < (L); i++)                                                           \
        acc = _mm_add_epi64(acc, t[i]);                                                 \
    return lh_finish128(acc, (uint64_t)len);                                            \
}

#if !defined(LH_VAES)
/* L = 4 (65..256 B): at most three full steps, written out. */
static inline __m128i lh_lanes4_xmm(const uint8_t *p, size_t len, uint64_t seed) {
    __m128i t0, t1, t2, t3, b, sd = _mm_set1_epi64x((long long)seed), ln = _mm_set1_epi64x((long long)len);
    size_t m = (len + 15) / 16 - 4, full = m / 4, rem = m % 4;
    const uint8_t *c = p + len - 64;
#define LH_STEP4(q) do {                                                                \
        b = _mm_loadu_si128((const __m128i *)(q)); LH_REG(b); t0 = _mm_aesenc_si128(_mm_xor_si128(t0, b), b); \
        b = _mm_loadu_si128((const __m128i *)((q) + 16)); LH_REG(b); t1 = _mm_aesenc_si128(_mm_xor_si128(t1, b), b); \
        b = _mm_loadu_si128((const __m128i *)((q) + 32)); LH_REG(b); t2 = _mm_aesenc_si128(_mm_xor_si128(t2, b), b); \
        b = _mm_loadu_si128((const __m128i *)((q) + 48)); LH_REG(b); t3 = _mm_aesenc_si128(_mm_xor_si128(t3, b), b); \
    } while (0)
    t0 = _mm_xor_si128(sd, LH_C128(0));
    t1 = _mm_xor_si128(sd, LH_C128(1));
    t2 = _mm_xor_si128(sd, LH_C128(2));
    t3 = _mm_xor_si128(sd, LH_C128(3));
    if (full >= 1) { LH_STEP4(p); p += 64; }
    if (full >= 2) { LH_STEP4(p); p += 64; }
    if (full >= 3) { LH_STEP4(p); p += 64; }
    if (rem >= 1) { b = _mm_loadu_si128((const __m128i *)p); LH_REG(b); t0 = _mm_aesenc_si128(_mm_xor_si128(t0, b), b); }
    if (rem >= 2) { b = _mm_loadu_si128((const __m128i *)(p + 16)); LH_REG(b); t1 = _mm_aesenc_si128(_mm_xor_si128(t1, b), b); }
    if (rem >= 3) { b = _mm_loadu_si128((const __m128i *)(p + 32)); LH_REG(b); t2 = _mm_aesenc_si128(_mm_xor_si128(t2, b), b); }
#undef LH_STEP4
    b = _mm_xor_si128(_mm_loadu_si128((const __m128i *)c), ln); LH_REG(b); t0 = _mm_aesenc_si128(_mm_xor_si128(t0, b), b);
    b = _mm_xor_si128(_mm_loadu_si128((const __m128i *)(c + 16)), ln); LH_REG(b); t1 = _mm_aesenc_si128(_mm_xor_si128(t1, b), b);
    b = _mm_xor_si128(_mm_loadu_si128((const __m128i *)(c + 32)), ln); LH_REG(b); t2 = _mm_aesenc_si128(_mm_xor_si128(t2, b), b);
    b = _mm_xor_si128(_mm_loadu_si128((const __m128i *)(c + 48)), ln); LH_REG(b); t3 = _mm_aesenc_si128(_mm_xor_si128(t3, b), b);
    {
        __m128i k0 = LH_C128(40), k1 = LH_C128(41), k2 = LH_C128(42);
        t0 = _mm_aesenc_si128(_mm_aesenc_si128(_mm_aesenc_si128(t0, k0), k1), k2);
        t1 = _mm_aesenc_si128(_mm_aesenc_si128(_mm_aesenc_si128(t1, k0), k1), k2);
        t2 = _mm_aesenc_si128(_mm_aesenc_si128(_mm_aesenc_si128(t2, k0), k1), k2);
        t3 = _mm_aesenc_si128(_mm_aesenc_si128(_mm_aesenc_si128(t3, k0), k1), k2);
    }
    return lh_finish128(_mm_add_epi64(_mm_add_epi64(t0, t1), _mm_add_epi64(t2, t3)), (uint64_t)len);
}
LH_DEFINE_XMM(lh_lanes8_xmm, 8, LH_ABSORB_REG)
LH_DEFINE_XMM(lh_lanes16_xmm, 16, LH_ABSORB_REG)
#endif /* !LH_VAES */

#if defined(LH_VAES)
/* ------------------------------------------------------------------------- */
/* lane path: VAES + AVX2, two lanes per ymm (L = 4, 8, 16)                     */

#define LH_C256(i) _mm256_broadcastsi128_si256(LH_C128(i))

#define LH_DEFINE_YMM(NAME, NR)                                                         \
static inline __m128i NAME(const uint8_t *p, size_t len, uint64_t seed) {                \
    __m256i t[NR], ln = _mm256_set1_epi64x((long long)len), acc;                        \
    __m128i sd = _mm_set1_epi64x((long long)seed);                                      \
    size_t n = (len + 15) / 16, m = n - 2 * (NR), full = m / (2 * (NR)), rem = m % (2 * (NR)), j; \
    const uint8_t *c = p + len - 32 * (NR);                                             \
    unsigned i, rr = (unsigned)(rem / 2), rp = (unsigned)(rem % 2);                     \
    LH_UNROLL for (i = 0; i < (NR); i++)                                                          \
        t[i] = _mm256_inserti128_si256(_mm256_castsi128_si256(_mm_xor_si128(sd, LH_C128(2 * i))), \
                                       _mm_xor_si128(sd, LH_C128(2 * i + 1)), 1);       \
    for (j = 0; j < full; j++, p += 32 * (NR))                                          \
        LH_UNROLL for (i = 0; i < (NR); i++) {                                                    \
            __m256i b = _mm256_loadu_si256((const __m256i *)(p + 32 * i));              \
            LH_REG(b);                                                                  \
            t[i] = _mm256_aesenc_epi128(_mm256_xor_si256(t[i], b), b);                  \
        }                                                                               \
    LH_UNROLL for (i = 0; i < rr; i++) {                                                          \
        __m256i b = _mm256_loadu_si256((const __m256i *)(p + 32 * i));                  \
        LH_REG(b);                                                                      \
        t[i] = _mm256_aesenc_epi128(_mm256_xor_si256(t[i], b), b);                      \
    }                                                                                   \
    if (rp) { /* one more block: low lane of register rr */                             \
        __m128i b = _mm_loadu_si128((const __m128i *)(p + 32 * rr));                    \
        __m128i lo = _mm_aesenc_si128(_mm_xor_si128(_mm256_castsi256_si128(t[rr]), b), b); \
        t[rr] = _mm256_inserti128_si256(t[rr], lo, 0);                                  \
    }                                                                                   \
    LH_UNROLL for (i = 0; i < (NR); i++) {                                                        \
        __m256i e = _mm256_xor_si256(_mm256_loadu_si256((const __m256i *)(c + 32 * i)), ln); \
        LH_REG(e);                                                                      \
        t[i] = _mm256_aesenc_epi128(_mm256_xor_si256(t[i], e), e);                      \
    }                                                                                   \
    LH_UNROLL for (i = 0; i < (NR); i++) {                                                        \
        t[i] = _mm256_aesenc_epi128(t[i], LH_C256(40));                                 \
        t[i] = _mm256_aesenc_epi128(t[i], LH_C256(41));                                 \
        t[i] = _mm256_aesenc_epi128(t[i], LH_C256(42));                                 \
    }                                                                                   \
    acc = t[0];                                                                         \
    for (i = 1; i < (NR); i++)                                                          \
        acc = _mm256_add_epi64(acc, t[i]);                                              \
    return lh_finish128(_mm_add_epi64(_mm256_castsi256_si128(acc), _mm256_extracti128_si256(acc, 1)), (uint64_t)len); \
}

LH_DEFINE_YMM(lh_lanes4_ymm, 2)
LH_DEFINE_YMM(lh_lanes8_ymm, 4)
LH_DEFINE_YMM(lh_lanes16_ymm, 8)
#endif /* LH_VAES */

static inline __m128i lh_lanes(const uint8_t *p, size_t len, uint64_t seed, unsigned L) {
#if defined(LH_VAES)
    if (L == 4)
        return lh_lanes4_ymm(p, len, seed);
    if (L == 8)
        return lh_lanes8_ymm(p, len, seed);
    return lh_lanes16_ymm(p, len, seed);
#else
    if (L == 4)
        return lh_lanes4_xmm(p, len, seed);
    if (L == 8)
        return lh_lanes8_xmm(p, len, seed);
    return lh_lanes16_xmm(p, len, seed);
#endif
}
static inline uint64_t lh_lanes64(const uint8_t *p, size_t len, uint64_t seed, unsigned L) {
    uint64_t lo; /* _mm_cvtsi128_si64 does not exist on 32-bit x86; this is one movq on x86-64 */
    _mm_storel_epi64((__m128i *)&lo, lh_lanes(p, len, seed, L));
    return lo;
}
static inline void lh_lanes128(const uint8_t *p, size_t len, uint64_t seed, unsigned L, uint8_t *out) {
    _mm_storeu_si128((__m128i *)out, lh_lanes(p, len, seed, L));
}

#endif /* LH_AESNI */

/* ------------------------------------------------------------------------- */
/* public API: prologue-free dispatchers, one out-of-line function per case so  */
/* each gets its own register allocation (the short path needs six callee-saved */
/* registers that the lane path would otherwise pay for too).                   */

static LH_NOINLINE uint64_t lh64_le16(const uint8_t *p, size_t len, uint64_t seed) { return lh_short_le16(p, len, seed, NULL); }
static LH_NOINLINE uint64_t lh64_le32(const uint8_t *p, size_t len, uint64_t seed) { return lh_short_le32(p, len, seed, NULL); }
static LH_NOINLINE uint64_t lh64_le64(const uint8_t *p, size_t len, uint64_t seed) { return lh_short_le64(p, len, seed, NULL); }
static LH_NOINLINE uint64_t lh64_l4(const uint8_t *p, size_t len, uint64_t seed) { return lh_lanes64(p, len, seed, 4); }
static LH_NOINLINE uint64_t lh64_l8(const uint8_t *p, size_t len, uint64_t seed) { return lh_lanes64(p, len, seed, 8); }
static LH_NOINLINE uint64_t lh64_l16(const uint8_t *p, size_t len, uint64_t seed) { return lh_lanes64(p, len, seed, 16); }

uint64_t lanehash_aes64(const void *key, size_t len, uint64_t seed) {
    const uint8_t *p = (const uint8_t *)key;
    if (len > 64) {
        if (len <= 256)
            return lh64_l4(p, len, seed);
        if (len <= 1024)
            return lh64_l8(p, len, seed);
        return lh64_l16(p, len, seed);
    }
    if (len <= 16)
        return lh64_le16(p, len, seed);
    if (len <= 32)
        return lh64_le32(p, len, seed);
    return lh64_le64(p, len, seed);
}

static LH_NOINLINE void lh128_short(const uint8_t *p, size_t len, uint64_t seed, uint8_t *o) {
    uint64_t hi, lo;
    if (len <= 16)
        lo = lh_short_le16(p, len, seed, &hi);
    else if (len <= 32)
        lo = lh_short_le32(p, len, seed, &hi);
    else
        lo = lh_short_le64(p, len, seed, &hi);
    lh_put64(o, lo);
    lh_put64(o + 8, hi);
}
static LH_NOINLINE void lh128_l4(const uint8_t *p, size_t len, uint64_t seed, uint8_t *o) { lh_lanes128(p, len, seed, 4, o); }
static LH_NOINLINE void lh128_l8(const uint8_t *p, size_t len, uint64_t seed, uint8_t *o) { lh_lanes128(p, len, seed, 8, o); }
static LH_NOINLINE void lh128_l16(const uint8_t *p, size_t len, uint64_t seed, uint8_t *o) { lh_lanes128(p, len, seed, 16, o); }

void lanehash_aes128(const void *key, size_t len, uint64_t seed, void *out) {
    const uint8_t *p = (const uint8_t *)key;
    uint8_t *o = (uint8_t *)out;
    if (len <= 64)
        lh128_short(p, len, seed, o);
    else if (len <= 256)
        lh128_l4(p, len, seed, o);
    else if (len <= 1024)
        lh128_l8(p, len, seed, o);
    else
        lh128_l16(p, len, seed, o);
}
